sudo: false

language: node_js

node_js:
  - 6 # Maintenance
  - 8 # Active
  - 10 # Current release

branches:
  only:
    - master
    - next

cache: npm

script:
  - npm run lint
  - npm run test:cov
  - npm run build

# Publish To NPM if push to master or next branch
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      node: '10'
      branch: 'master'
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: next
    on:
      node: '10'
      branch: 'next'

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

after_success:
  - npm run codecov
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    # Only send notifications when travis status changes
    on_failure: change
    on_success: change
